/**
 * Core type definitions for the Family Tree frontend.
 * These mirror the backend types and add frontend-specific types.
 */

export type Gender = 'male' | 'female';

/**
 * Person represents an individual in the family tree.
 */
export interface Person {
  id: string;
  name: string;
  gender: Gender;
  spouseId?: string;
  childrenIds: string[];
  birthDate?: string;
  alive?: boolean;
  imageUrl?: string;
}

/**
 * FamilyTree represents the complete family data structure.
 */
export interface FamilyTree {
  _id: string;
  name: string;
  ownerId?: string;
  isPublic?: boolean;
  shareToken?: string;
  people: Record<string, Person>;
  rootId: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Layout node with computed position for rendering.
 * Generated by the layout engine.
 */
export interface LayoutNode {
  person: Person;
  x: number;
  y: number;
  width: number;
  height: number;
  // Relationship context
  isSpouse: boolean;
  isChild: boolean;
  isParent: boolean;
  isFocused: boolean;
  // For animations
  generation: number;
}

/**
 * Connection line between family members.
 */
export interface Connection {
  id: string;
  type: 'spouse' | 'parent-child';
  from: { x: number; y: number };
  to: { x: number; y: number };
  fromId: string;
  toId: string;
}

/**
 * Layout result from the layout engine.
 */
export interface LayoutResult {
  nodes: LayoutNode[];
  connections: Connection[];
  bounds: {
    minX: number;
    maxX: number;
    minY: number;
    maxY: number;
    width: number;
    height: number;
  };
  focusedNode: LayoutNode | null;
}

/**
 * Transform state for pan and zoom.
 */
export interface TransformState {
  x: number;
  y: number;
  scale: number;
}

/**
 * Navigation history entry.
 */
export interface NavigationEntry {
  personId: string;
  timestamp: number;
}

/**
 * Tree summary for listing.
 */
export interface TreeSummary {
  _id: string;
  name: string;
  rootId: string;
  peopleCount: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * API response wrapper.
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Modal state for CRUD operations.
 */
export interface ModalState {
  type: 'add-spouse' | 'add-child' | 'add-parent' | 'add-first-person' | 'edit-person' | 'delete-person' | 'create-tree' | null;
  personId?: string;
  isOpen: boolean;
}

/**
 * Form data for creating/editing persons.
 */
export interface PersonFormData {
  name: string;
  gender: Gender;
  birthDate?: string;
  alive: boolean;
  imageUrl?: string;
}

